### ISSUE TITLE
Scanner takes time to scan qrcode 

### ISSUE THREAD

**Issue by E-Kelly2018** [yuriy-budiyev/code-scanner#42]
First off thank you for the library 
My problem is the Qr code reading take quite a while to read anything up to 30 seconds is there a fix for this using version 2.0.1

**Comment by yuriy-budiyev** [comment]
It can take diferent time on diferent devices, depending on their cameras and other things. I can do nothing against that in most situations because I'm using ZXing library do decode images.

**Comment by rexdarel** [comment]
@yuriy-budiyev you are right. I tried different libraries, I thought it could be the library that is slow... but it turns out that they are the same, it takes so much time to decode the qr code. So, It could be the device I am using. Cheers. I went back to use this one anyway, since it has better ui than the other libraries.
